### ISSUE TITLE
astropy 4.0 incompatibity

### ISSUE THREAD

**Issue by profxj** [noaodatalab/datalab#10]
Because astropy eliminated astropy.extern.six,
the utils.py module in dl/helpers/ fails on import
if one is using the latest, stable astropy package.

Might be time for this repository to end its Python 2 support.

**Comment by mjfitzpatrick** [comment]
The dependency on astropy.extern.six has been removed from the dl/helpers/utils.py file.  The code change was minor and can be retrieved from the git repo using:

    % git clone https://github.com/noaodatalab/datalab
    % cd datalab
    % python setup.py install

This should install v2.17.3 containing the fix.  Please let us know if you find any other problems.
