### ISSUE TITLE
Compatibility with Python 3.7

### ISSUE THREAD

**Issue by Thalos12** [noaodatalab/datalab#3]
I would like to point out that async queries with `datalab` do not work with Python 3.7 since in this version `async` is a reserved keyword ([Summary – Release Highlights](https://docs.python.org/3/whatsnew/3.7.html#summary-release-highlights)).

The issue was also reported in the old `datalab-client` github page ([issue 2](https://github.com/noaodatalab-user/datalab-client/issues/3)).

It could be useful to emphasize this incompatibility in the README of the repository and possibly in the [documentation](https://datalab.noao.edu/docs/manual/UsingTheNOAODataLab/InstallDatalab/InstallDatalab.html).

Thanks for your time.

**Comment by rnikutta** [comment]
Async does work. Please be sure to have the latest version of the 'datalab' command:

`$datalab version`
Task Version:  2.16.0

With it, make sure you are logged in:

`$datalab whoami`

If it is 'anonymous':

`$datalab login`

Then, for instance:

`$datalab query --sql='select ra,dec from smash_dr1.object limit 10' --async=true`

returns a jobID. After a few seconds, check if async job is completed:

`$datalab qstatus --jobID=foobar # use the jobid returned previously`

and if that is 'COMPLETED', you can retrieve the results via:

`$datalab qresults --jobID=foobar # again use previous jobID string`.

Please let us know if you still experience trouble.

**Comment by Thalos12** [comment]
I did not notice that I had another version! Now it works as I expected. Thanks for the help.
