### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by santiagogil96** [noaodatalab/datalab#37]
Hello,

Since yesterday I've been getting the following connection error in python:

`ConnectionError: HTTPSConnectionPool(host='datalab.noao.edu', port=443): Max retries exceeded with url: /query/query?sql=%0A++++++++SELECT+des_sva1.mag_auto_g++++++++FROM+des_sva1.gold_catalog+AS+des_sva1%0A++++++++LIMIT+300000%0A++++++++&ofmt=csv&out=None&async=False&drop=False&profile=default (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f10f1743160>: Failed to establish a new connection: [Errno -2] Name or service not known'))
`

I think it has something to do with the switching from noao to noirlab servers. 
Any way to solve this?

Thanks.

**Comment by rnikutta** [comment]
Thank you for reaching out. With the move to the noirlab.edu domain, and the release of v2.20.0 of the `datalab` package, the connection errors should be gone. Closing this ticket, but please let us know if you encounter more problems. (In case you are upgrading to v2.20.0 from a prior version, please see in READMe.md the new note about updating your local dl.conf file). 
Thank you!
