### ISSUE TITLE
Connection error in new version due to dl.conf

### ISSUE THREAD

**Issue by Thalos12** [noaodatalab/datalab#39]
As in #37, I was getting the connection error, but I noticed that a new version of the package was coming. I tried v2.20.0 as soon as I could, but it showed the same error. The root of the issue was that the file `$HOME/.datalab/dl.conf` contained the old URLs (https://datalab.noao.edu/).
Maybe it could be mentioned in the README that users upgrading from older versions should delete or move that file?

**Comment by rnikutta** [comment]
Thank you for the heads-up. We have added to README.md a paragraph on updating dl.conf if one upgraded `datalab` from a version prior to v2.20.0. Many thanks!
