### ISSUE TITLE
Update the installation instructions.

### ISSUE THREAD

**Issue by Thalos12** [noaodatalab/datalab#4]
The instructions for installation of datalab found [here](https://datalab.noao.edu/docs/manual/UsingTheNOAODataLab/InstallDatalab/InstallDatalab.html) point to the old package and the old GitHub repository.

**Comment by rnikutta** [comment]
Updated. Corrected version deployed. Thank you for the heads-up, we much appreciate it!

**Comment by Thalos12** [comment]
Thanks to you for making such a useful tool!

**Comment by nicwolf** [comment]
Hi Robert,

There's also a reference to the old client here: https://datalab.noao.edu/docs/manual/UsingTheNOAODataLab/CommandLineTools/TheDatalabCommand/TheDatalabCommand.html in section 1.7.1.1. I ended up scratching my head for a while with the same problem in #3 after installing the old client.

I'd be happy to submit a PR if you'd point me toward the documentation source (doesn't seem to be in this repo?)

Best,
