### ISSUE TITLE
Log in fails

### ISSUE THREAD

**Issue by steveschulze** [noaodatalab/datalab#41]
Hi,

I installed version 2.19.2 on python 3.7 and 3.8. When I do `datalab` or `datalab status`, I get the webpage's output. I always fail to log in. The error message is:

```
datalab login
user (default: None): USERNAME
password (default: None): PASSWORD
login error: tok = AuthManager Service not responding.
AuthManager Service not responding.

```
This error also occurs after removing $HOME/.datalab.

Do you have a suggestion about what might cause this problem?

Cheers,

Steve

**Comment by steveschulze** [comment]
Hi Robert,

Thanks. I installed the new version. I tried to log in but my account was suspended after the first attempt:

datalab login
user (default: None): USERNAME
password (default: None): PASSWORD
login error: tok = Error: Account is suspended
Error: Account is suspended

Who do I have to contact to unlock my account?

Cheers,

Steve

**Comment by mjfitzpatrick** [comment]
Hi Steve,

Your account has been reactivated, please let us know if you continue to
have problems.

Cheers,
-Mike

**Comment by steveschulze** [comment]
Hi Mike and Robert,

It worked. Thanks a lot for quick help!

Cheers,

Steve
