### ISSUE TITLE
Does multimethod have unreachable code?

### ISSUE THREAD

**Issue by weaverba137** [noaodatalab/datalab#43]
I'm concerned about number of argument errors when attempting to test functions wrapped by multimethod.  Based on [this line](https://github.com/noaodatalab/datalab/blob/0b2ab502d8b543f6527d5f6d6a4933e198863b7f/dl/Util.py#L141) in `dl.Util.multimethod()`, it seems like the code below never gets called.  Is this intentional?  

In general, where are some good examples of how to use `multimethod()` on module level functions versus *instance* methods and versus *class* methods?

**Comment by mjfitzpatrick** [comment]
This was tracked to a bug in the multimethod code that was fixed in toymanager and later checked into the datalab client.  Tests with use in toymanager demonstrate it working correctly now.
