### ISSUE TITLE
IllegalArgumentException: net.sf.jsqlparser.JSQLParserException JSQLParserException

### ISSUE THREAD

**Issue by paolosoto** [noaodatalab/datalab#46]
Hi, I have a problem with the q3c_dist function, for some reason the jsqlparser throw a ParseException:

`Error: IllegalArgumentException: net.sf.jsqlparser.JSQLParserException JSQLParserException: ParseException: Encountered "(" at line 1, column 98. Was expecting one of: <EOF> "ASC" ... "DESC" ... "LIMIT" ... "OFFSET" ... ";" ... "," ... "." ... "UNION" ...`

Seems don't recognize that function because without these I dont have problems. The code for this :

```
ssql = '''SELECT * FROM decaps_dr1.object AS g WHERE q3c_join(10, 20, g.ra, g.dec, 0) ORDER BY q3c_dist(0, 0, 0, 0)'''

jobid = qc.query(sql=ssql, async_=True)

while qc.status(jobid) != 'COMPLETED':

         print(qc.status(jobid))

         print(qc.error(jobid))

         time.sleep(2)

```
The version of the datalab package :

`noaodatalab               2.20.0 
`
Regards!

**Comment by paolosoto** [comment]
I have detected that the problem is with the async_ flag. In sync mode doesn't exist the problem.

**Comment by mjfitzpatrick** [comment]
In the current system, async queries are processed by our TAP service, whereas sync queries (i.e. async_=False) are sent directly to the database.  The query is converted to ADQL for TAP processing, and even though the q3c_dist() function is an extension we've made to our ADQL, functions are not permitted by the ADQL syntax as arguments to an 'ORDER BY' clause (only column names or unsigned integers are permitted).

Additionally, your example query appears invalid in the sense that all the args to the q3c_dist() function are zero (resulting in a zero return always) and the q3c_join() has a zero radius (resulting in no output).  Is this what you intended or was the code truncated somehow?

To work around the issue, submit the query synchronously.  If you encounter a timeout condition, you can extend the query time by adding a 'timeout' parameter of up to 10 minutes, e.g.

`qc.query (sql=ssql, timeout=600)`

Hope this helps.

**Comment by paolosoto** [comment]
oh!!.. thanks, now I understand.

And yes, with a higher timeout it works.

thanks!
