### ISSUE TITLE
hostname issue or installation issue?

### ISSUE THREAD

**Issue by caseyjlaw** [noaodatalab/datalab#8]
Hello,
  I am using Python 3.6 and installed datalab via pip. Trying a simple import gives me this error:
```
> python -c 'from dl import queryClient as qc'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/claw/anaconda3/envs/py36/lib/python3.6/site-packages/dl/queryClient.py", line 105, in <module>
    from dl import storeClient
  File "/Users/claw/anaconda3/envs/py36/lib/python3.6/site-packages/dl/storeClient.py", line 120, in <module>
    THIS_IP   = socket.gethostbyname(socket.gethostname())  # host IP address
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

  Any idea what might cause that?
  I installed first a while ago and I do recall that there were some significant changes. I did an update today that found lots of changes, so perhaps there are some issues with dependencies.

**Comment by lijuan** [comment]
What os do you use? This link might be useful to you:
https://apple.stackexchange.com/questions/253817/cannot-ping-my-local-machine

**Comment by caseyjlaw** [comment]
This is a new macbook running OSX and, indeed, turning on file sharing fixed it. Thanks so much!
I had no idea this was a requirement for some networking services.
